version: 2
aliases:
  - &node_version node:8.11.3
  # Common steps
  - &restore_npm_cache
    restore_cache:
      name: Restore npm dependencies cache
      key: npm-dependency-{{ checksum "package.json" }}
  - &restore_uitest_npm_cache
    restore_cache:
      name: Restore uitest npm dependencies cache
      key: uitest-npm-dependency-{{ checksum "package.json" }}

jobs:
  dependencies:
    docker:
      - image: *node_version
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *restore_npm_cache
      - run: npm install
      - save_cache:
          name: Save npm dependencies cache
          key: npm-dependency-{{ checksum "package.json" }}
          paths:
            - ~/data-science-frontend/node_modules

  lint_test:
    docker:
      - image: *node_version
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Lint code
          command: npm run lint
          when: always

  unit_test:
    docker:
      - image: *node_version
        environment:
           TZ: "/usr/share/zoneinfo/Europe/London"
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Jest tests
          command: npm run test
          when: always

  functional_test:
    docker:
      - image: *node_version
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *restore_npm_cache
      - *restore_uitest_npm_cache
      - run:
          name: Cypress tests
          command: |
            cd uiTest
            npm install
            cd ..
            xvfb-run ./run-functional-tests-ci.sh
          when: always

workflows:
  version: 2
  datasciencefe:
    jobs:
      - dependencies
      - lint_test:
          requires:
            - dependencies
      - unit_test:
          requires:
            - dependencies
      - functional_test:
          requires:
            - lint_test
            - unit_test
