version: 2
aliases:
  - &node_version  node:10.16.0
  - &redis_version redis:3.2.10
  # Common steps
  - &restore_npm_cache
    restore_cache:
      name: Restore npm dependencies cache
      key: npm-dependency-{{ checksum "package.json" }}-{{ checksum "node_version" }}-{{ checksum "npm_version" }}
  - &store_versions
    run:
      name: Temporarily store node/npm versions on filesystem
      command: node --version > node_version; npm --version > npm_version
  - &restore_end_to_end_npm_cache
    restore_cache:
      name: Restore end to end test npm dependencies cache
      key: webdriverio-npm-dependency-{{ checksum "package.json" }}

  # Data hub base docker container
  - &docker_data_hub_base
    image: ukti/data-hub-frontend-test:2.0.0

  # Data hub redis container
  - &docker_redis
    image: *redis_version

  - &docker_dt07_api_sandbox
    image: ukti/find-exporters-sandbox:latest

  - &wait_for_api_sandbox
    run:
      name: Wait for api sandbox
      command: dockerize -wait ${BACKEND_URL}/ping.xml -timeout 120s

  - &find_exporters_base_envs
    BACKEND_URL: http://localhost:8002
    LOG_LEVEL: debug
    SSO_BYPASS: true
    SESSION_SECRET: x
    SSO_DOMAIN: x
    SSO_CLIENT: x
    SSO_SECRET: x
    SSO_PATH_AUTH: x
    SSO_PATH_TOKEN: x
    SSO_PATH_INTROSPECT: x
    SSO_REDIRECT_URI: x
    BACKEND_KEY: x
    BACKEND_USER: x
    NODE_ENV: development
    TZ: Europe/London

  - &find_exporters_e2e_envs
    BACKEND_URL: https://dt07-staging.london.cloudapps.digital
    LOG_LEVEL: debug
    SSO_BYPASS: true
    SESSION_SECRET: x
    SSO_DOMAIN: x
    SSO_CLIENT: x
    SSO_SECRET: x
    SSO_PATH_AUTH: x
    SSO_PATH_TOKEN: x
    SSO_PATH_INTROSPECT: x
    SSO_REDIRECT_URI: x
    BACKEND_KEY: x
    BACKEND_USER: prospects

jobs:
  dependencies:
    docker:
      - image: *node_version
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *store_versions
      - *restore_npm_cache
      - run: npm install
      - save_cache:
          name: Save npm dependencies cache
          key: npm-dependency-{{ checksum "package.json" }}-{{ checksum "node_version" }}-{{ checksum "npm_version" }}
          paths:
            - ~/data-science-frontend/node_modules
            - /root/.cache/Cypress

  lint_test:
    docker:
      - image: *node_version
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *store_versions
      - *restore_npm_cache
      - run:
          name: Lint code
          command: npm run lint
          when: always

  unit_test:
    docker:
      - image: *node_version
        environment:
          <<: *find_exporters_base_envs
          REDIS_CACHING_DISABLED: true
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *store_versions
      - *restore_npm_cache
      - run:
          name: Jest tests
          command: npm run test
          when: always

  functional_test:
    docker:
      - <<: *docker_data_hub_base
        environment:
          <<: *find_exporters_base_envs
          REDIS_CACHING_DISABLED: false
      - *docker_redis
      - *docker_dt07_api_sandbox
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *store_versions
      - *restore_npm_cache
      - *wait_for_api_sandbox
      - run:
          name: Cypress tests
          command: ./run-functional-tests-ci.sh
          when: always
      - store_artifacts:
          path: cypress/screenshots

  end_to_end_test:
    docker:
      - image: ukti/data-sci-end-to-end
        environment: *find_exporters_e2e_envs
    working_directory: ~/data-science-frontend
    steps:
      - checkout
      - *store_versions
      - *restore_npm_cache
      - *restore_end_to_end_npm_cache
      - run:
          name: End to end dependencies
          command: |
            cd uiTest/end-to-end
            npm install
      - run:
          name: Webdriverio tests
          command: ./run-end-to-end-tests-ci.sh
          when: always
      - save_cache:
          name: Save functional test npm dependencies cache
          key: webdriverio-npm-dependency-{{ checksum "package.json" }}
          paths:
            - ~/data-science-frontend/uiTest/end-to-end/node_modules
          when: always

workflows:
  version: 2
  datasciencefe:
    jobs:
      - dependencies
      - lint_test:
          requires:
            - dependencies
      - unit_test:
          requires:
            - dependencies
      - functional_test:
          requires:
            - lint_test
            - unit_test
      - end_to_end_test:
          requires:
            - functional_test
